/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softech.FrameApp.ui.Admin;


import com.softech.FrameApp.bean.DanhMucBean;
import com.softech.FrameApp.controller.ChuyenManHinhAdmin;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author leduc
 */
public class MainJFrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainJFrameAdmin() {
        initComponents();
        
        ChuyenManHinhAdmin controllerAdmin = new ChuyenManHinhAdmin(jlbView);
        controllerAdmin.setView(jpnHomeAdmin, jlbHomeAdmin);
       
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("TrangChuAdmin", jpnHomeAdmin, jlbHomeAdmin));
        listItem.add(new DanhMucBean("ChinhSuaThongTinNguoiDung", jpnChinhSuaThongTinNguoiDung, jlbChinhSuaThongTinNguoiDung));
        
        controllerAdmin.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jpnRoot = new javax.swing.JPanel();
        jlbView = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpnChinhSuaThongTinNguoiDung = new javax.swing.JPanel();
        jlbChinhSuaThongTinNguoiDung = new javax.swing.JLabel();
        jpnQLVaccine = new javax.swing.JPanel();
        jlbQLVaccine = new javax.swing.JLabel();
        jpnHomeAdmin = new javax.swing.JPanel();
        jlbHomeAdmin = new javax.swing.JLabel();
        jpnThongKe = new javax.swing.JPanel();
        jlbThongKe = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jlbViewLayout = new javax.swing.GroupLayout(jlbView);
        jlbView.setLayout(jlbViewLayout);
        jlbViewLayout.setHorizontalGroup(
            jlbViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 984, Short.MAX_VALUE)
        );
        jlbViewLayout.setVerticalGroup(
            jlbViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpnMenu.setBackground(new java.awt.Color(82, 83, 81));

        jPanel13.setBackground(new java.awt.Color(255, 0, 0));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(232, 64, 60));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/appqlsv/icons/laptop-screen.png"))); // NOI18N
        jLabel7.setText("Quản Trị Viên");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnChinhSuaThongTinNguoiDung.setBackground(new java.awt.Color(76, 175, 80));
        jpnChinhSuaThongTinNguoiDung.setForeground(new java.awt.Color(255, 255, 255));

        jlbChinhSuaThongTinNguoiDung.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbChinhSuaThongTinNguoiDung.setForeground(new java.awt.Color(255, 255, 255));
        jlbChinhSuaThongTinNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/appqlsv/icons/user32.png"))); // NOI18N
        jlbChinhSuaThongTinNguoiDung.setText("Chỉnh sửa thông tin người dùng");

        javax.swing.GroupLayout jpnChinhSuaThongTinNguoiDungLayout = new javax.swing.GroupLayout(jpnChinhSuaThongTinNguoiDung);
        jpnChinhSuaThongTinNguoiDung.setLayout(jpnChinhSuaThongTinNguoiDungLayout);
        jpnChinhSuaThongTinNguoiDungLayout.setHorizontalGroup(
            jpnChinhSuaThongTinNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChinhSuaThongTinNguoiDungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbChinhSuaThongTinNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnChinhSuaThongTinNguoiDungLayout.setVerticalGroup(
            jpnChinhSuaThongTinNguoiDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnChinhSuaThongTinNguoiDungLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbChinhSuaThongTinNguoiDung)
                .addContainerGap())
        );

        jpnQLVaccine.setBackground(new java.awt.Color(76, 175, 80));

        jlbQLVaccine.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbQLVaccine.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLVaccine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/appqlsv/icons/user32.png"))); // NOI18N
        jlbQLVaccine.setText("Quản lý vaccine");

        javax.swing.GroupLayout jpnQLVaccineLayout = new javax.swing.GroupLayout(jpnQLVaccine);
        jpnQLVaccine.setLayout(jpnQLVaccineLayout);
        jpnQLVaccineLayout.setHorizontalGroup(
            jpnQLVaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLVaccineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbQLVaccine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnQLVaccineLayout.setVerticalGroup(
            jpnQLVaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLVaccineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbQLVaccine)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnHomeAdmin.setBackground(new java.awt.Color(76, 175, 80));

        jlbHomeAdmin.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbHomeAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jlbHomeAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/appqlsv/icons/user32.png"))); // NOI18N
        jlbHomeAdmin.setText("Màn hình chính");

        javax.swing.GroupLayout jpnHomeAdminLayout = new javax.swing.GroupLayout(jpnHomeAdmin);
        jpnHomeAdmin.setLayout(jpnHomeAdminLayout);
        jpnHomeAdminLayout.setHorizontalGroup(
            jpnHomeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHomeAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHomeAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnHomeAdminLayout.setVerticalGroup(
            jpnHomeAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHomeAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHomeAdmin)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnThongKe.setBackground(new java.awt.Color(76, 175, 80));

        jlbThongKe.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbThongKe.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/softech/appqlsv/icons/user32.png"))); // NOI18N
        jlbThongKe.setText("Thống kê số liệu");

        javax.swing.GroupLayout jpnThongKeLayout = new javax.swing.GroupLayout(jpnThongKe);
        jpnThongKe.setLayout(jpnThongKeLayout);
        jpnThongKeLayout.setHorizontalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnThongKeLayout.setVerticalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongKeLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jlbThongKe)
                .addContainerGap())
        );

        btnLogOut.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnLogOut.setText("Đăng xuất");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnExit.setText("Thoát");

        btnChangePassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnChangePassword.setText("Đổi mật khẩu");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChangePassword)
                .addGap(15, 15, 15))
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnQLVaccine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnHomeAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnChinhSuaThongTinNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnChangePassword, btnExit, btnLogOut});

        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jpnHomeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jpnChinhSuaThongTinNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jpnQLVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jpnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogOut)
                    .addComponent(btnChangePassword))
                .addGap(48, 48, 48)
                .addComponent(btnExit)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlbView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Hệ thống");

        jMenuItem1.setText("Đăng xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Thoát");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Thông tin");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrameAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JLabel jlbChinhSuaThongTinNguoiDung;
    private javax.swing.JLabel jlbHomeAdmin;
    private javax.swing.JLabel jlbQLVaccine;
    private javax.swing.JLabel jlbThongKe;
    private javax.swing.JPanel jlbView;
    private javax.swing.JPanel jpnChinhSuaThongTinNguoiDung;
    private javax.swing.JPanel jpnHomeAdmin;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnQLVaccine;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnThongKe;
    // End of variables declaration//GEN-END:variables
}
